# Reference
- https://pytorch.org/docs/0.4.0/nn.html
- https://pytorch.org/tutorials/
- https://ratsgo.github.io/machine%20learning/2017/10/12/terms/
- https://github.com/DSKSD/Pytorch_Fast_Campus_2018

In [2]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import numpy as np
from collections import OrderedDict

torch.manual_seed(1)

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# What is a PyTorch?
- Tensor와 Optimizer, Neural Net등 GPU연산에 최적화된 모듈을 이용하여 빠르게 딥러닝 모델을 구현할 수 있는 프레임워크
Facebook이 밀고 있던 lua기반의 torch를 python버전으로 포팅함.

# > Pytorch Basic
- Tensor
- autograd
- nn
- optim

## 1. Tensor

wiki >
 - 텐서란 선형 관계를 나타내는 기학적 대상이다.  
 (https://ko.wikipedia.org/wiki/%ED%85%90%EC%84%9C#%EC%A0%95%EC%9D%98)
 
PyTorch > 
 - Tensor는 N차원 배열이며, PyTorch는 Tensor연산을 위한 다양한 함수들을 제공함.   
 - numpy와 다르게 GPU를 활용해 수치 연산을 가속화 할 수 있음.  
 
### 1.1 Create tensor
- 다양한 방법으로 Tensor타입의 자료형을 만들 수 있음.

#### 1.1.1 파이썬 리스트로부터 생성

In [16]:
V_data= [1., 2., 3.] 
V= torch.Tensor(V_data).int()
print('<vector> %s %s:\n' ,V, V.dtype)

V_data= [1, 2, 3] 
V= torch.Tensor(V_data).float()
print('<vector> %s %s:\n' ,V, V.dtype)

M_data= [[1.,2.,3.],[4.,5.,6.]] # 매트릭스
M= torch.Tensor(M_data)
print('<matrix> %s %s:\n', M, M.dtype)

T_data= [[[1.,2.],[3.,4.]],[[4.,5.],[6.,7.]]]
T= torch.Tensor(T_data)
print('<3d Tensor> :\n', T)

T_data= T.tolist()
print('<Tensor->list>:\n', T_data)

<vector> %s %s:
 tensor([1, 2, 3], dtype=torch.int32) torch.int32
<vector> %s %s:
 tensor([1., 2., 3.]) torch.float32
<matrix> %s %s:
 tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.float32
<3d Tensor> :
 tensor([[[1., 2.],
         [3., 4.]],

        [[4., 5.],
         [6., 7.]]])
<Tensor->list>:
 [[[1.0, 2.0], [3.0, 4.0]], [[4.0, 5.0], [6.0, 7.0]]]


#### 1.1.2  numpy ndarray객체로부터 Tensor생성

In [22]:
# vector
V_data= np.array([1., 2., 3.]) 
V= torch.Tensor(V_data)
print('<vector> %s %s:\n' ,V, V.dtype)

# 매트릭스
M_data= np.array([
    [1.,2.,3.],[4.,5.,6.]
]) 
M= torch.Tensor(M_data)
print('<matrix> %s %s:\n', M, M.dtype)

# 3d tensor
T_data= np.array([
    [[1.,2.],[3.,4.]],
    [[4.,5.],[6.,7.]]
])
T= torch.Tensor(T_data)
print('<3d Tensor> %s %s:\n', T, T.dtype)


T_data= T.numpy()
print('<Tensor->numpy ndarray>: %s %s\n', T_data, T_data.dtype)

<vector> %s %s:
 tensor([1., 2., 3.]) torch.float32
<matrix> %s %s:
 tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.float32
<3d Tensor> %s %s:
 tensor([[[1., 2.],
         [3., 4.]],

        [[4., 5.],
         [6., 7.]]]) torch.float32
<Tensor->numpy ndarray>: %s %s
 [[[1. 2.]
  [3. 4.]]

 [[4. 5.]
  [6. 7.]]] float32


#### 1.1.3 기타 다른 생성 방법들

In [25]:
x= torch.zeros(2,3)
print('<zeros tensor> :\n', x)

x= torch.ones(2,3)
print('<ones tensor> :\n', x)

x= torch.randn(3,4) 
print('<sample Normal distribution> :\n', x)

x= torch.randperm(5)
print('<permutation of integers from 0 to n-1(LongTenosr)> :\n', x)

<zeros tensor> :
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
<ones tensor> :
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
<sample Normal distribution> :
 tensor([[ 0.4107, -0.9880, -0.9081,  0.5423],
        [ 0.1103, -2.2590,  0.6067, -0.1383],
        [ 0.8310, -0.2477, -0.8029,  0.2366]])
<permutation of integers from 0 to n-1(LongTenosr)> :
 tensor([1, 0, 4, 2, 3])


### 1.2. Indexing, Slicing, Joining, Mutating Ops
- PyTorch의 Tensor 자료형도 numpy의 ndarray와 같이 indexing, slicing, joining이 가능함.  

#### 1.2.1. indexing

In [29]:
x= torch.randn(3,4,5)
print(x)
print(x.shape)
print(x.size())
print(x[0,:,:].size())

tensor([[[ 2.4142,  1.0206, -0.4405, -1.7342, -1.0257],
         [ 0.5213, -0.4531, -0.1260, -0.5882,  2.1189],
         [-0.5422, -2.4593, -0.9502, -0.3095,  1.6633],
         [ 0.5051, -0.1970, -0.0334,  0.7193,  1.0644]],

        [[-0.8336, -1.1929, -2.3065,  0.6037,  0.3151],
         [ 1.1423,  0.3055, -0.5789,  0.5644, -0.8773],
         [-0.2693,  1.3120, -1.5563, -1.0757, -0.8752],
         [-0.4728, -0.7531, -0.4319,  0.6693,  0.6505]],

        [[ 0.7879,  1.3686, -0.8507,  0.5126,  0.6522],
         [-0.8726,  0.0353, -0.3365,  1.4023,  0.4841],
         [-0.7030, -0.8268,  0.7744,  0.6920, -1.0185],
         [-0.8034, -0.7071,  0.7521, -0.0192,  1.1033]]])
torch.Size([3, 4, 5])
torch.Size([3, 4, 5])
torch.Size([4, 5])


#### 1.2.2 select_index
- LongTensor로 Tensor에 행 또는 열에 해당하는 값을 가져올 수 있음.

In [28]:
x= torch.randn(3,4)
print('x.shape :',x.shape)
print('x :',x)
indices= torch.LongTensor([0,2])
print('indices:', indices)
print('')
print('select 0 dim: ', torch.index_select(x, 0, indices))
print('select 1 dim: ', torch.index_select(x, 1, indices))

x.shape : torch.Size([3, 4])
x : tensor([[ 0.3482,  1.1371, -0.3339, -1.4724],
        [ 0.7296, -0.1312, -0.6368,  1.0429],
        [ 0.4903,  1.0318, -0.5989,  1.6015]])
indices: tensor([0, 2])

select 0 dim:  tensor([[ 0.3482,  1.1371, -0.3339, -1.4724],
        [ 0.4903,  1.0318, -0.5989,  1.6015]])
select 1 dim:  tensor([[ 0.3482, -0.3339],
        [ 0.7296, -0.6368],
        [ 0.4903, -0.5989]])


#### 1.2.3 torch.masked_select
- torch.Tenosr타입의 ge메소드는 인자값보다 큰 경우를 1 작은 경우를 0인 동일한 크기의 Tensor를 생성함.
- masked_select는 마스킹된 값을 Tensor로 반환함.

In [32]:
x= torch.randn(3,4)
print('tensor :\n',x)

mask= x.ge(0.5)
print('ge method\n', mask)

print(torch.masked_select(x,mask))

tensor :
 tensor([[-0.8996,  0.5313,  0.4034,  1.4521],
        [-2.4182, -1.1906,  0.6964,  1.1296],
        [ 0.2214, -0.0558,  1.2057,  1.9486]])
ge method
 tensor([[0, 1, 0, 1],
        [0, 0, 1, 1],
        [0, 0, 1, 1]], dtype=torch.uint8)
tensor([0.5313, 1.4521, 0.6964, 1.1296, 1.2057, 1.9486])


#### 1.2.4 torch.cat
- Tensor들을 concatenate함

In [45]:
x_1= torch.rand(2,5)
y_1= torch.rand(3,5)
y_2= torch.rand(2,3)
z_1= torch.cat([x_1, y_1],0) #0: row cat
z_2= torch.cat([x_1, y_2],1) #1: column cat
print(x_1)
print(y_1)
print(z_1)
print(z_1.size())
print('------------')
print(x_1)
print(y_2)
print(z_2)
print(z_2.size())

tensor([[0.9647, 0.2933, 0.7951, 0.5170, 0.2801],
        [0.8339, 0.1185, 0.2355, 0.5599, 0.8966]])
tensor([[0.2858, 0.1955, 0.1808, 0.2796, 0.3273],
        [0.3835, 0.2156, 0.6563, 0.5041, 0.1733],
        [0.2145, 0.6059, 0.4929, 0.8539, 0.4242]])
tensor([[0.9647, 0.2933, 0.7951, 0.5170, 0.2801],
        [0.8339, 0.1185, 0.2355, 0.5599, 0.8966],
        [0.2858, 0.1955, 0.1808, 0.2796, 0.3273],
        [0.3835, 0.2156, 0.6563, 0.5041, 0.1733],
        [0.2145, 0.6059, 0.4929, 0.8539, 0.4242]])
torch.Size([5, 5])
------------
tensor([[0.9647, 0.2933, 0.7951, 0.5170, 0.2801],
        [0.8339, 0.1185, 0.2355, 0.5599, 0.8966]])
tensor([[0.0949, 0.1302, 0.3532],
        [0.3893, 0.5571, 0.3879]])
tensor([[0.9647, 0.2933, 0.7951, 0.5170, 0.2801, 0.0949, 0.1302, 0.3532],
        [0.8339, 0.1185, 0.2355, 0.5599, 0.8966, 0.3893, 0.5571, 0.3879]])
torch.Size([2, 8])


#### 1.2.5 torch.view
- Tensor를 reshape함.

In [47]:
x= torch.randn(2,3,4)
print(x.size())
print(x.view(2,-1).size()) # make (3,4) flatted. i.e. make (3,4) matrix into 1 vector
print('--------')
print(x)
print(x.view(2,-1))

torch.Size([2, 3, 4])
torch.Size([2, 12])
--------
tensor([[[-1.8161,  0.8735, -1.0497,  0.8341],
         [ 1.5750, -0.5619, -1.8470, -0.5632],
         [ 1.2100, -0.9293,  1.5965, -0.0352]],

        [[ 0.1928,  0.9446, -0.0364,  0.9030],
         [ 1.6241, -1.9684,  0.9299,  1.5981],
         [ 0.4262,  2.5073,  0.3480, -0.0482]]])
tensor([[-1.8161,  0.8735, -1.0497,  0.8341,  1.5750, -0.5619, -1.8470, -0.5632,
          1.2100, -0.9293,  1.5965, -0.0352],
        [ 0.1928,  0.9446, -0.0364,  0.9030,  1.6241, -1.9684,  0.9299,  1.5981,
          0.4262,  2.5073,  0.3480, -0.0482]])


#### 1.2.6 torch.squeeze
- Tensor에서 차원을 제거함. [[1]]->[1]

In [65]:
# question: x.squeeze(2) 의 의미는?
x= torch.ones(3,1,3)
print(x.size())
print(x.squeeze(dim=1).size())
print('--------')
print(x)
print(x.squeeze(dim=1))

torch.Size([3, 1, 3])
torch.Size([3, 3])
--------
tensor([[[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


#### 1.2.7 torch.unsqueeze
- Tensor에서 차원을 추가함. [1]->[[1]]

In [63]:
print(x.size())
print(x.unsqueeze(1).size())
print('--------')
print(x)
print(x.unsqueeze(dim=1))

torch.Size([3, 1, 3])
torch.Size([3, 1, 1, 3])
--------
tensor([[[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]]])
tensor([[[[1., 1., 1.]]],


        [[[1., 1., 1.]]],


        [[[1., 1., 1.]]]])


### 1.3 Math Operation
- Tensor타입을 연산할 수 있음.

#### 1.3.1 add
- 텐서의 각 scalar값을 각 element별로 더해줌

In [66]:
x= torch.Tensor([1,2,3])
y= torch.Tensor([3,4,5])
z=x+y
print(z)
print(torch.add(x,y))

tensor([4., 6., 8.])
tensor([4., 6., 8.])


#### 1.3.2 sum
- Tensor의 모든 scalar값을 더해준다.

In [67]:
x= torch.Tensor([1.,2.,3.])
print(x.sum())
print(sum(x))

tensor(6.)
tensor(6.)


#### 1.3.3 dot product 
- Tensor들끼리 dot product를 한다.

In [68]:
x= torch.Tensor([1.,2.,3.])
y= torch.Tensor([1.,2.,3.])
z= x.dot(y)
print(z)
print(torch.dot(x,y))

tensor(14.)
tensor(14.)


#### 1.3.4 mul
- Tensor들의 각 scalara값들을 element마다 곱해줌.

In [69]:
x= torch.Tensor([1,2,3])
y= torch.Tensor([3,4,5])
z= x.mul(y)
print(z)

tensor([ 3.,  8., 15.])


#### 1.3.5 mm : matrix multiplication
- matrix multiplication

In [70]:
x= torch.randn(2,3)
y= torch.randn(3,2)
z= x.mm(y)
print(x)
print(y)
print('=')
print(z)
print(z.size())

tensor([[-0.1130, -0.2160,  1.1587],
        [ 1.2181, -0.5526, -0.6075]])
tensor([[-0.0905, -0.8301],
        [-0.0809, -2.5912],
        [-0.2716, -1.8131]])
=
tensor([[-0.2870, -1.4475],
        [ 0.0995,  1.5224]])
torch.Size([2, 2])


#### 1.3.6 max 
- scalar 값 중에서 max값을 구해준다.

In [71]:
x= torch.Tensor([[1,2], [3,4], [5,1]])
print(x.max()) # 전체 기준 max
# dim 은 counter-intuitive 하다...
print(x.max(0)) # 차원을 기준해서 max와 그에 해당하는 index
print(x.max(1))

tensor(5.)
(tensor([5., 4.]), tensor([2, 1]))
(tensor([2., 4., 5.]), tensor([1, 1, 0]))
